/* 5d6230d39c839343c1124e30868669f4c81529b1
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import * as Apollo from '@apollo/client';
export declare type GroupsQueryVariables = Types.Exact<{
  text?: Types.InputMaybe<Types.Scalars['String']>;
  orderBy?: Types.InputMaybe<Array<Types.QueryTypesOrderByOrderByClause> | Types.QueryTypesOrderByOrderByClause>;
  language?: Types.InputMaybe<Types.Scalars['String']>;
}>;
export declare type GroupsQuery = {
  __typename?: 'Query';
  types: Array<{
    __typename?: 'Type';
    id: string;
    name: string;
    slug: string;
    language: string;
    icon: string;
    banners?: Array<{
      __typename?: 'Banner';
      id: string;
      title?: string | null;
      image: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      };
    }> | null;
    settings?: {
      __typename?: 'TypeSettings';
      isHome: boolean;
      layoutType: string;
      productCard: string;
    } | null;
  }>;
};
export declare type GroupQueryVariables = Types.Exact<{
  slug?: Types.InputMaybe<Types.Scalars['String']>;
  language?: Types.InputMaybe<Types.Scalars['String']>;
}>;
export declare type GroupQuery = {
  __typename?: 'Query';
  type: {
    __typename?: 'Type';
    id: string;
    slug: string;
    name: string;
    language: string;
    banners?: Array<{
      __typename?: 'Banner';
      id: string;
      title?: string | null;
      description?: string | null;
      image: {
        __typename?: 'Attachment';
        id?: string | null;
        original?: string | null;
        thumbnail?: string | null;
      };
    }> | null;
    promotional_sliders?: Array<{
      __typename?: 'Attachment';
      id?: string | null;
      thumbnail?: string | null;
      original?: string | null;
    }> | null;
  };
};
export declare const GroupsDocument: Apollo.DocumentNode;
/**
 * __useGroupsQuery__
 *
 * To run a query within a React component, call `useGroupsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGroupsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGroupsQuery({
 *   variables: {
 *      text: // value for 'text'
 *      orderBy: // value for 'orderBy'
 *      language: // value for 'language'
 *   },
 * });
 */

export declare function useGroupsQuery(baseOptions?: Apollo.QueryHookOptions<GroupsQuery, GroupsQueryVariables>): Apollo.QueryResult<GroupsQuery, Types.Exact<{
  text?: Types.InputMaybe<string> | undefined;
  orderBy?: Types.InputMaybe<Types.QueryTypesOrderByOrderByClause | Types.QueryTypesOrderByOrderByClause[]> | undefined;
  language?: Types.InputMaybe<string> | undefined;
}>>;
export declare function useGroupsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GroupsQuery, GroupsQueryVariables>): Apollo.QueryTuple<GroupsQuery, Types.Exact<{
  text?: Types.InputMaybe<string> | undefined;
  orderBy?: Types.InputMaybe<Types.QueryTypesOrderByOrderByClause | Types.QueryTypesOrderByOrderByClause[]> | undefined;
  language?: Types.InputMaybe<string> | undefined;
}>>;
export declare type GroupsQueryHookResult = ReturnType<typeof useGroupsQuery>;
export declare type GroupsLazyQueryHookResult = ReturnType<typeof useGroupsLazyQuery>;
export declare type GroupsQueryResult = Apollo.QueryResult<GroupsQuery, GroupsQueryVariables>;
export declare const GroupDocument: Apollo.DocumentNode;
/**
 * __useGroupQuery__
 *
 * To run a query within a React component, call `useGroupQuery` and pass it any options that fit your needs.
 * When your component renders, `useGroupQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGroupQuery({
 *   variables: {
 *      slug: // value for 'slug'
 *      language: // value for 'language'
 *   },
 * });
 */

export declare function useGroupQuery(baseOptions?: Apollo.QueryHookOptions<GroupQuery, GroupQueryVariables>): Apollo.QueryResult<GroupQuery, Types.Exact<{
  slug?: Types.InputMaybe<string> | undefined;
  language?: Types.InputMaybe<string> | undefined;
}>>;
export declare function useGroupLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GroupQuery, GroupQueryVariables>): Apollo.QueryTuple<GroupQuery, Types.Exact<{
  slug?: Types.InputMaybe<string> | undefined;
  language?: Types.InputMaybe<string> | undefined;
}>>;
export declare type GroupQueryHookResult = ReturnType<typeof useGroupQuery>;
export declare type GroupLazyQueryHookResult = ReturnType<typeof useGroupLazyQuery>;
export declare type GroupQueryResult = Apollo.QueryResult<GroupQuery, GroupQueryVariables>;